version: '3.3'
services:
    test:
        network_mode: host
        image: robot
        shm_size: "512M"
        environment:
            USERNAME: mnpawan
        volumes: [
           "$PWD/config:/config",
           "$PWD/output:/output",
           "$PWD/resources:/resources",
           "$PWD/tests:/tests"

        ]